development:
  adapter: postgresql
  encoding: unicode
  database: poopgraph_development

test: &test
  adapter: postgresql
  encoding: unicode
  database: poopgraph_test

production:
  adapter: postgresql
  encoding: unicode
  database: poopgraph_production

cucumber:
  <<: *test